docs: make editorial updates
terraform-ibm-modules/terraform-ibm-satellite pull request #63
Opened 2022-07-06 20:19 UTC by SirSpidey

Fixed some typos and grammar issues. Modified to fit better to IBM style.

2023-02-28 23:00 UTC, finken2 requested changes
@SirSpidey I realize this is ancient at this point, but if you're still interested in merging, would you mind updating the occurrences of satellite to Satellite?  It's a product name.

2023-03-01 22:02 UTC, SirSpidey commented
@finken2 Thanks. Made that change and a few other minor editorial changes.

2023-03-03 14:16 UTC, finken2 requested changes

2023-03-03 14:16 UTC, finken2 commented on README.md
> +- *Conditionally creates* of these items:
grammar doesn't work here.

2023-03-03 14:16 UTC, finken2 commented on README.md
> +Use this Terraform automation to set up a Satellite location on IBM cloud. The module provisions the IBM Cloud® Satellite location, creates 6 VSIs, assigns three hosts to the control plane, provision
some inconsistency on "IBM Cloud" here and a little lower down.  First sentence, Cloud should be capitalized.  Second sentence, the trademark symbol is there, but it's removed down on line 14.

2023-03-03 14:16 UTC, finken2 commented on README.md
> +This module is a collection of submodules that make it easier to provision a Satellite on IBM Cloud.
"provision a Satellite" doesn't really make sense.  We could say "provision Satellite resources" to cover the fact it does a location, hosts, cluster, etc

2023-03-03 14:16 UTC, finken2 commented on README.md
> +- The `location` submodule creates a location or uses an existing location ID or name. If you pass an existing location, the submodule produces an error and exits the module. To fix the issue, set `i
i'm not sure why they originally wrote this from the standpoint of how to make it error. Up to you, but we could just state the two different possibilities: new location or use existing.

2023-03-03 14:16 UTC, finken2 commented on README.md
> +- All optional fields are set to `null` in the `variable.tf` file. You can overwrite the values.
variables.tf (with an s).  Probably override, not overwrite.

2023-03-03 14:16 UTC, finken2 commented on README.md
> +All optional parameters are set to null by default in the example's `variable.tf` file. If you want to configure an optional parameter, overwrite the default value.
variables.tf w/ an s.
override instead of overwrite.

2023-03-03 14:51 UTC, SirSpidey commented
@finken2 thanks for paying attention to this. I wasn't intending to rewrite this content because my team isn't responsible for this module. I was trying to suggest some small changes that I noticed while making some other changes through the "TIM" GH org.

2023-03-03 15:25 UTC, finken2 approved these changes

2023-03-03 15:38 UTC, merged